import json
from ollama import chat

## System prompt for the Planner Agent
## Describe its role, the expected output format, and the rules it must follow when generating a navigation plan.
## These are fairly similar to the Analyst Agent, but with a focus on creating a plan based on the requirements provided by the Analyst Agent.


## Function to validate the plan generated by the Planner Agent
## It should first check that the parameter it receives is of the correct type. 
# Then, it should validate all the keys and values contained in the above Python data structure of the input parameter.
def validate_plan(data):
    pass


## Function to run the Planner Agent
## It takes the requirements generated by the Analyst Agent as input, sends them to the Planner Agent. Just like you did with the Analyst Agent.
## Take the response from the Planner Agent (Qwen), parse it and validate it using the validate_plan function, and return the validated plan.
def run_planner(requirement):
    pass